apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-academia
spec:
  selector:
    matchLabels:
      app: front-academia
  template:
    metadata:
      labels:
        app: front-academia
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: front-academia
        image: ghcr.io/pablosmolak/academia-front:latest
        resources: {}
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: envfile
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: envfile
        secret:
          secretName: front-academia-envfile

---
apiVersion: v1
kind: Service
metadata:
  name: front-academia
  labels:
    rubix.expose: "true"
spec:
  type: ClusterIP
  selector:
    app: front-academia
  ports:
  - port: 80
    targetPort: 3000
